### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by bobbybee** [nathan/pixie#163]
What's the development status of pixie at the moment? Halted due to real life?

Also, if that's the case, is there any good place to start on a fork (and what is your pull request policy)?

**Comment by nathan** [comment]
> Halted due to real life?

Something like that. The open issues should give you a pretty good idea of what's missing. Pull request policy is "if I have time to look at it and it's reasonable," but you can always just keep going on your fork.

**Comment by bobbybee** [comment]
@nathan Cool. To be fair, I'm probably as busy as you are, but... maybe I can maintain something reasonably active :)

**Comment by IronManMark20** [comment]
@nathan , @bobbybee  I have invited you both to an organization, so that we can have multiple maintainers. That way things will be easier to keep going even if Nathan or another maintainer isn't around, and pull requests can be accepted. I have already imported pixie, and I will be adding a Visual repo. What do you think? I think it would be a good base while Nathan is busy.

**Comment by bobbybee** [comment]
@IronManMark20 It's not worth it tbh; that creates more problems than it solves.

I'll fork it if I get anywhere, although it's really not that much work for @nathan to review code periodically to push up mainstream.

I don't feel any changes need to be made at the moment :smile:

**Comment by IronManMark20** [comment]
@bobbybee , Okay, nevermind. Ill just delete it. I thought I would propose it as a solution to speed things up. No problem.

**Comment by q2dg** [comment]
Maybe it's worthy have a look to https://github.com/jmoenig/Snap--Build-Your-Own-Blocks ...
